name: Auto Deploy Play Store

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Java 8 (compatible)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3. Instalar Gradle
      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      # 4. Instalar Fastlane
      - name: Install Fastlane
        run: sudo gem install fastlane

      # 5. Crear keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-key.jks

      # 6. Build DIRECTO (sin wrapper)
      - name: Build AAB
        run: |
          gradle clean
          gradle bundleRelease --no-daemon

      # 7. Deploy
      - name: Deploy to Play Store
        run: fastlane deploy
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
